--- #YAML:1.0
name:               MySQL-Util
version:            0.10
abstract:           Utility functions for working with MySQL.
author:
    - John Gravatt <gravattj@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Compare:        1.22
    DBD::mysql:           0
    Moose:                1.24
    namespace::autoclean:  0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
